- Type: Training
  Trainers:
    - Name: Abraham Aranguren
      Email: admin@7asecurity.com
      Image: /assets/images/trainers/trainer-abraham-aranguren.png
      Twitter: 7ASecurity
      Biography: "After 13 years in itsec and 20 in IT Abraham is now the CEO of 7ASecurity (7asecurity.com), a company specializing 
        in penetration testing of web/mobile apps, infrastructure, code reviews and training. Former senior penetration tester / team 
        lead at Cure53 (cure53.de) and Version 1 (www.version1.com). Creator of 'Practical Web Defense' - a hands-on eLearnSecurity 
        attack / defense course (www.elearnsecurity.com/PWD), OWASP OWTF project leader, an OWASP flagship project (owtf.org), Major 
        degree and Diploma in Computer Science, some certs: CISSP, OSCP, GWEB, OSWP, CPTS, CEH, MCSE:Security, MCSA:Security, 
        Security+. As a shell scripting fan trained by unix dinosaurs, Abraham wears a proud manly beard. He writes on Twitter as 
        @7asecurity @7a_ @owtfp or https://7asecurity.com/blog. Multiple presentations, pentest reports and recordings can be found 
        at https://7asecurity.com/publications"
      TrainerId: abraham_aranguren
  Title: "Hacking Modern Web apps: Master the Future of Attack Vectors"
  URL: /register/?id=sku_HOtoAiWFO6u23G
  SectionId: sku_HOtoAiWFO6u23G
  Description: "This course is a 100% hands-on deep dive into the OWASP Security Testing Guide and relevant items of the OWASP Application 
    Security Verification Standard (ASVS), so this course covers and goes beyond the OWASP Top Ten.<br>
    Long are the days since web servers were run by perl scripts. What is common between Walmart, eBay, PayPal, Microsoft, LinkedIn, Google 
    and Netflix? They all use Node.js: JavaScript on the server.<br>
    Modern Web apps share traditional attack vectors and also introduce new opportunities to threat actors. This course will teach you how 
    to review modern web apps, showcasing Node.js but using techniques that will also work against any other web app platform. Ideal for 
    Penetration Testers, Web app Developers as well as everybody interested in JavaScript/Node.js app security.<br>
    All action, no fluff, improve your security analysis workflow and immediately apply these gained skills in your workplace, packed with 
    exercises, extra mile challenges and CTF, self-paced and suitable for all skill levels, with continued education via unlimited email 
    support and lifetime access to training portal with step-by-step video recordings and interesting apps to practice, including all future 
    updates for free."
- Type: Training
  Trainers:
    - Name: Keatron Evans
      Email: kevans@kmcybersecurity.com
      Image: /assets/images/trainers/trainer-keatron-evans.jpg
      Twitter: kmcybersecurity
      Biography: "Keatron Evans is the Managing Partner at KM Cyber Security, LLC, https://kmcybersecurity.com, and responsible for 
                global information security consulting business which includes penetration testing, cyber threat hunting, digital forensics, 
                and training. He regularly consults for and trains members of the intelligence community of the US and other governments in 
                offensive cyber operations and works on several classified threat hunting operations each year. Keatron is also one of the 
                authors of the award-winning Certified Ethical Hacking course administered by the Infosec Institute. Additionally, he is the 
                lead author of Chained Exploits: Advancing Hacking Attacks from Start to Finish, a textbook still used for offensive training 
                throughout academic and corporate communities."
      TrainerId: keatron_evans
  Title: From OWASP Top 10 To Command Shell
  URL: /register/?id=sku_HOtp0eVxTbZwFj
  SectionId: sku_HOtp0eVxTbZwFj
  Description: "This will be a hands-on lab driven technical deep-dive.  From XSS, SQLi, To Complete System Compromise. We will examine several 
    common OWASP Top 10 vulnerabilities, then go deeper by obtaining shell access, then root/system level control of the owned devices. These 
    techniques are often game-changers when explaining the vulnerabilities to others."
- Type: Training
  Trainers:
    - Name: Tanya Janca
      Email: tanya.janca@owasp.org
      Image: /assets/images/trainers/trainer-tanya-janca.jpg
      Twitter: shehackspurple
      Biography: "Tanya Janca, also known as ‘SheHacksPurple’, is the founder, 
        security trainer and coach of SheHacksPurple.dev, specializing in software 
        and cloud security. Her obsession with securing software runs deep, from 
        starting her company, to running her own OWASP chapter for 4 years in Ottawa,
         co-founding a new OWASP chapter in Victoria, and co-founding the OWASP 
         DevSlop open-source and education project. With her countless blog articles, 
         workshops and talks, her focus is clear. Tanya is also an advocate for 
         diversity and inclusion, co-founding the international women’s organization 
         WoSEC, starting the online #CyberMentoringMonday initiative, and personally 
         mentoring, advocating for and enabling countless other women in her field. 
         As a professional computer geek of 20+ years, she is a person who is truly 
         fascinated by the ‘science’ of computer science."
      TrainerId: tanya_janca
  Title: Application Security 101
  URL: /register/?id=sku_HOts6ZxZnmJERL
  SectionId: sku_HOts6ZxZnmJERL
  Description: "<ol><li>What is AppSec, What is DevSecOps, Why do they matter? - A tiny bit of history, quite a few definitions.</li>
    <li>The Goals of any AppSec Program - We will set our own goals to bring back to work, which we will add to, update, improve and plan throughout the training.</li>
    <li>Types of AppSec Activities - What do they actually mean, how to do you do them and which ones do you *need* to do.</li>
    <li>Types of AppSec Tooling, what they do, when you may or may not need them, approximate costs for budgeting purposes</li>
    <li>Scaling your team: Security Champions, delegation, automation and coaching</li>
    <li>Developer Education - What to teach, how to teach, and why.</li>
    <li>Setting Standards and Policies (with take home examples to start you off)</li>
    <li>Metrics and Improvement - Learn which metrics really matter, how to measure, and then how to use your data to improve your program to reach maximum efficiency and security.</li>
    <li>Goals: time to adjust, improve, and make a complete plan to achieve your AppSec goals.</li></ol>"
- Type: Training
  Trainers:
    - Name: Jason Kent
      Email: jason.kent@cequence.ai
      Image: /assets/images/trainers/trainer-jason-kent.jpg
      Twitter: cyber_nsa
      Biography: For over the last 20 years, Jason has been ethically peering into 
        Client Behavior, Wireless Networks, Web Applications, APIs and Cloud Systems, 
        helping organizations secure their assets and intellectual property from 
        unauthorized access.  As a consultant he's taken hundreds of organizations 
        through difficult compliance mine fields, ensuring their safety.  As a 
        researcher he has found flaws in consumer IOT systems and assisted in hardening 
        them against external attacks.  At Cequence Security Jason does research, 
        community outreach and supports efforts in identifying Automated Attacks against 
        Web, Mobile, and API-based Applications to keep Cequence's customers safe.
      TrainerId: jason_kent
  Title: API Attacks Beyond the OWASP API Top 10
  URL: /register/?id=sku_HOtty6RFWsLTAd
  SectionId: sku_HOtty6RFWsLTAd
  Description: "Let’s face it, APIs are running the world.  3rd party integrations are everywhere from social media communication to integrations 
    allowing services to share platforms and data.  As developers race to create platforms with greater connectivity and functionality, shortcuts are 
    taken, errors are made, specifications ignore – resulting in the release of insecure APIs.  No longer are front end services and frameworks enough 
    to protect the APIs from new world, high-speed attacks.<br>
    Over the last 20 years as a hacker, researcher, and educator I have worked with many organizations to help them stop high-speed attacks as well as 
    sophisticated fraudsters that are constantly on the lookout for the next venue to ply their trade.  In addition to case studies derived from actual 
    attacks I will show how I was able to attack a garage door opener API and via responsible disclosure create a much safer platform for Chamberlain 
    customers/users to control entry into their homes.<br>
    In this 8-hour class we will talk about API attacks my company has seen against different types of platforms and compare common real-world attack 
    types to the API Top 10.<br>
    We will look at taking apart Android API calls, utilizing an open-source APK disassembly tool, for mobile applications and understand the attack 
    surface available.  This tool will be distributed via a docker container so students should have the ability to run a docker.<br>
    From a web application standpoint we will learn how to analyze API calls, API parameters and how to utilize simple tools like cURL or your favorite 
    intercept proxy, to make calls against APIs and understand the workflow to test against a range of use cases such as Account Take Over, Inventory 
    Take Over/Seat Spinning, Inventory Take Over, etc.<br>
    Attackers often have tools at their disposal that target specific organizations, we will highlight these tools and how they work.<br>
    Finally, we will look at some Case Studies from various places that we have seen attacks occur and current attack campaigns that have thwarted the 
    efforts of many security practitioners and development staff.  We will have a cloud environment built allowing for newly minted API security 
    enthusiasts to try techniques and view their attacks and fingerprints in real time."
- Type: Training
  Trainers:
    - Name: Mohammed Abdul Imran
      Email: imran@practical-devsecops.com
      Image: /assets/images/trainers/trainer-mohammed-imran.jpg
      Twitter: secfigo
      Biography: "Mohammed A. 'secfigo' Imran is the Founder and CEO of Practical DevSecOps 
        and seasoned security professional with over a decade of experience in helping 
        organizations in their Information Security Programs.<br> 
        He has a diverse background in R&D, consulting, and product-based companies with a 
        passion for solving complex security programs. Imran is the founder of Null 
        Singapore, the most significant information security community in Singapore, where 
        he has organized more than 60 events & workshops to spread security awareness.<br>
        He was also nominated as a community star for being the go-to person in the 
        community whose contributions and knowledge sharing has helped many professionals 
        in the security industry.<br>
        He is usually seen speaking and giving training in conferences like Blackhat, 
        DevSecCon, AppSec, All Day DevOps, Nullcon, and many other international conferences."
      TrainerId: mohammed_imran
  Title: Continuous Compliance at DevOps speed
  URL: /register/?id=sku_HOtw118RzSkqiw
  SectionId: sku_HOtw118RzSkqiw
  Description: "Have you experienced the challenge of communicating and collaborating with Compliance teams being as clear as mud?<br>
    We've all been there. In this training session, we'll learn how to use CNCF OPA (Open 
    Policy Agent) and Chef Inspec to verify the Compliance status of cloud resources 
    against standards such as Cloud Security Alliance CCM (Cloud Security Matrix) and AWS 
    Security Maturity Roadmap so we can help break some of the communication barriers with 
    Compliance teams, as they get an immediate understanding of the compliance status of 
    products and services.<br>
    Compliance is a major driver for investing in security for most businesses, and with 
    the growing number of systems and applications managing compliance of thousands of 
    systems without automation is not practical and Compliance teams are under immense 
    pressure to ensure successful audit outcomes, as failure to be compliant, can have 
    significant business impact. With Compliance as Code we can increase the speed of 
    delivery, mitigate lack of resources and time by-using checks across applications, 
    provide faster feedback to engineers, scale to hundreds or thousands of systems and 
    make the whole process easily auditable.<br>
    In this training, we will learn how to create and verify the compliance checks, 
    integrate them into CI/CD platform and also how we can leverage the use of metadata to 
    tag resources with all the compliance checks and standards they're meeting as we deploy 
    them in our cloud accounts in order to enable both engineering and compliance teams to 
    have the visibility they require for assurance of their cloud security posture.<br>
    The participants will perform all hands-on exercises in our state of the art browser 
    based labs."
